version: '3.8'

services:
  db:
    image: postgres:15
    container_name: zschool_db
    environment:
      POSTGRES_DB: zschool
      POSTGRES_USER: zschool_user
      POSTGRES_PASSWORD: zschool_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - zschool_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zschool_user -d zschool"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: zschool_backend
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://zschool_user:zschool_password@db:5432/zschool
      - HF_TOKEN=${HF_TOKEN}
      - CANVAS_BEARER_TOKEN=${CANVAS_BEARER_TOKEN}
      - ENVIRONMENT=development
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - zschool_network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: zschool_frontend
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8001
      - REACT_APP_ENVIRONMENT=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - zschool_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  zschool_network:
    driver: bridge 