name: zschool
services:
- name: backend
  source_dir: /backend
  github:
    branch: main
    deploy_on_push: true
  build_command: pip install -r requirements.txt
  run_command: uvicorn main:app --host 0.0.0.0 --port 8080
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  health_check:
    http_path: /health
  envs:
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    value: ${db.DATABASE_URL}
  - key: HF_TOKEN
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: XAI_TOKEN
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: CANVAS_BEARER_TOKEN
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: CANVAS_USER_ID
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: ENVIRONMENT
    scope: RUN_AND_BUILD_TIME
    value: production

- name: frontend
  source_dir: /frontend
  github:
    branch: main
    deploy_on_push: true
  build_command: npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 80
  routes:
  - path: /
  envs:
  - key: REACT_APP_API_URL
    scope: BUILD_TIME
    value: ${backend.PUBLIC_URL}
  - key: REACT_APP_ENVIRONMENT
    scope: BUILD_TIME
    value: production

databases:
- name: db
  engine: PG
  version: "15"
  size: basic-xs
  num_nodes: 1 